name: Publish

on:
  push:
    branches:
      - main

jobs:
  Docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login (GHCR)
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: metadata
        name: Get Metadata
        uses: docker/metadata-action@v4
        with:
          flavor: |
            latest=auto
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=sha

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2

      - id: build
        name: Build
        uses: docker/build-push-action@v3
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          labels: ${{ steps.metadata.outputs.label }}
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
